package net.evrem.service.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the GridItem service. Represents a row in the &quot;grid_item&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link net.evrem.service.model.impl.GridItemModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link net.evrem.service.model.impl.GridItemImpl}.
 * </p>
 *
 * @author Zdenek Vecek
 * @see GridItem
 * @see net.evrem.service.model.impl.GridItemImpl
 * @see net.evrem.service.model.impl.GridItemModelImpl
 * @generated
 */
public interface GridItemModel extends BaseModel<GridItem> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a grid item model instance should use the {@link GridItem} interface instead.
     */

    /**
     * Returns the primary key of this grid item.
     *
     * @return the primary key of this grid item
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this grid item.
     *
     * @param primaryKey the primary key of this grid item
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the grid item ID of this grid item.
     *
     * @return the grid item ID of this grid item
     */
    public long getGridItemId();

    /**
     * Sets the grid item ID of this grid item.
     *
     * @param gridItemId the grid item ID of this grid item
     */
    public void setGridItemId(long gridItemId);

    /**
     * Returns the note ID of this grid item.
     *
     * @return the note ID of this grid item
     */
    public long getNoteId();

    /**
     * Sets the note ID of this grid item.
     *
     * @param noteId the note ID of this grid item
     */
    public void setNoteId(long noteId);

    /**
     * Returns the w of this grid item.
     *
     * @return the w of this grid item
     */
    public int getW();

    /**
     * Sets the w of this grid item.
     *
     * @param w the w of this grid item
     */
    public void setW(int w);

    /**
     * Returns the h of this grid item.
     *
     * @return the h of this grid item
     */
    public int getH();

    /**
     * Sets the h of this grid item.
     *
     * @param h the h of this grid item
     */
    public void setH(int h);

    /**
     * Returns the x of this grid item.
     *
     * @return the x of this grid item
     */
    public int getX();

    /**
     * Sets the x of this grid item.
     *
     * @param x the x of this grid item
     */
    public void setX(int x);

    /**
     * Returns the y of this grid item.
     *
     * @return the y of this grid item
     */
    public int getY();

    /**
     * Sets the y of this grid item.
     *
     * @param y the y of this grid item
     */
    public void setY(int y);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(GridItem gridItem);

    @Override
    public int hashCode();

    @Override
    public CacheModel<GridItem> toCacheModel();

    @Override
    public GridItem toEscapedModel();

    @Override
    public GridItem toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
