package net.evrem.service.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the TodoNote service. Represents a row in the &quot;todo_note&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link net.evrem.service.model.impl.TodoNoteModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link net.evrem.service.model.impl.TodoNoteImpl}.
 * </p>
 *
 * @author Zdenek Vecek
 * @see TodoNote
 * @see net.evrem.service.model.impl.TodoNoteImpl
 * @see net.evrem.service.model.impl.TodoNoteModelImpl
 * @generated
 */
public interface TodoNoteModel extends BaseModel<TodoNote> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a todo note model instance should use the {@link TodoNote} interface instead.
     */

    /**
     * Returns the primary key of this todo note.
     *
     * @return the primary key of this todo note
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this todo note.
     *
     * @param primaryKey the primary key of this todo note
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the todo note ID of this todo note.
     *
     * @return the todo note ID of this todo note
     */
    public long getTodoNoteId();

    /**
     * Sets the todo note ID of this todo note.
     *
     * @param todoNoteId the todo note ID of this todo note
     */
    public void setTodoNoteId(long todoNoteId);

    /**
     * Returns the note ID of this todo note.
     *
     * @return the note ID of this todo note
     */
    public long getNoteId();

    /**
     * Sets the note ID of this todo note.
     *
     * @param noteId the note ID of this todo note
     */
    public void setNoteId(long noteId);

    /**
     * Returns the is done of this todo note.
     *
     * @return the is done of this todo note
     */
    public boolean getIsDone();

    /**
     * Returns <code>true</code> if this todo note is is done.
     *
     * @return <code>true</code> if this todo note is is done; <code>false</code> otherwise
     */
    public boolean isIsDone();

    /**
     * Sets whether this todo note is is done.
     *
     * @param isDone the is done of this todo note
     */
    public void setIsDone(boolean isDone);

    /**
     * Returns the text of this todo note.
     *
     * @return the text of this todo note
     */
    @AutoEscape
    public String getText();

    /**
     * Sets the text of this todo note.
     *
     * @param text the text of this todo note
     */
    public void setText(String text);

    /**
     * Returns the sort no of this todo note.
     *
     * @return the sort no of this todo note
     */
    public int getSortNo();

    /**
     * Sets the sort no of this todo note.
     *
     * @param sortNo the sort no of this todo note
     */
    public void setSortNo(int sortNo);

    /**
     * Returns the modified date of this todo note.
     *
     * @return the modified date of this todo note
     */
    public Date getModifiedDate();

    /**
     * Sets the modified date of this todo note.
     *
     * @param modifiedDate the modified date of this todo note
     */
    public void setModifiedDate(Date modifiedDate);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(TodoNote todoNote);

    @Override
    public int hashCode();

    @Override
    public CacheModel<TodoNote> toCacheModel();

    @Override
    public TodoNote toEscapedModel();

    @Override
    public TodoNote toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
