package net.evrem.service.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import net.evrem.service.model.GridItem;
import net.evrem.service.service.GridItemLocalServiceUtil;

/**
 * The extended model base implementation for the GridItem service. Represents a row in the &quot;grid_item&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link GridItemImpl}.
 * </p>
 *
 * @author Zdenek Vecek
 * @see GridItemImpl
 * @see net.evrem.service.model.GridItem
 * @generated
 */
public abstract class GridItemBaseImpl extends GridItemModelImpl
    implements GridItem {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a grid item model instance should use the {@link GridItem} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            GridItemLocalServiceUtil.addGridItem(this);
        } else {
            GridItemLocalServiceUtil.updateGridItem(this);
        }
    }
}
