package net.evrem.service.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import net.evrem.service.model.Note;
import net.evrem.service.service.NoteLocalServiceUtil;

/**
 * The extended model base implementation for the Note service. Represents a row in the &quot;note&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link NoteImpl}.
 * </p>
 *
 * @author Zdenek Vecek
 * @see NoteImpl
 * @see net.evrem.service.model.Note
 * @generated
 */
public abstract class NoteBaseImpl extends NoteModelImpl implements Note {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a note model instance should use the {@link Note} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            NoteLocalServiceUtil.addNote(this);
        } else {
            NoteLocalServiceUtil.updateNote(this);
        }
    }
}
