package net.evrem.service.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import net.evrem.service.model.RemindInfo;
import net.evrem.service.service.RemindInfoLocalServiceUtil;

/**
 * The extended model base implementation for the RemindInfo service. Represents a row in the &quot;remind_info&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link RemindInfoImpl}.
 * </p>
 *
 * @author Zdenek Vecek
 * @see RemindInfoImpl
 * @see net.evrem.service.model.RemindInfo
 * @generated
 */
public abstract class RemindInfoBaseImpl extends RemindInfoModelImpl
    implements RemindInfo {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a remind info model instance should use the {@link RemindInfo} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            RemindInfoLocalServiceUtil.addRemindInfo(this);
        } else {
            RemindInfoLocalServiceUtil.updateRemindInfo(this);
        }
    }
}
