package net.evrem.service.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import net.evrem.service.model.TodoNote;
import net.evrem.service.service.TodoNoteLocalServiceUtil;

/**
 * The extended model base implementation for the TodoNote service. Represents a row in the &quot;todo_note&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TodoNoteImpl}.
 * </p>
 *
 * @author Zdenek Vecek
 * @see TodoNoteImpl
 * @see net.evrem.service.model.TodoNote
 * @generated
 */
public abstract class TodoNoteBaseImpl extends TodoNoteModelImpl
    implements TodoNote {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a todo note model instance should use the {@link TodoNote} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            TodoNoteLocalServiceUtil.addTodoNote(this);
        } else {
            TodoNoteLocalServiceUtil.updateTodoNote(this);
        }
    }
}
